LPC/Django/noticias/projeto_noticias/urls.py
from django.contrib import admin
from django.urls import path, include

from app_noticias.views import *

urlpatterns = [
    path('', resumo_template, name='resumo'),
    path('admin/', admin.site.urls),
    path('noticia/<int:noticia_id>', detalhes_noticia, name = 'detalhe'),
    path('conta/', include('django.contrib.auth.urls')),
    path('contato/', ContatoView, name="contato"),
    path('contato/salvar', salvarMensagem, name="salvarMensagem"),
    path('tag', tag, name='tag'),
    path('tags/adicionar', salvarTag, name="salvarTag"),
    path('adicionarNoticia', addNoticia, name="adicionarNoticia"),
    path('noticia/adicionar', postarNoticia, name="postarNoticia"),
    path('minhasNoticias/editar/salvarEdicao', postarNoticiaEditada, name="postarNoticiaEditada"),
    path('noticia/delete', deleteNoticia, name="deleteNoticias"),
    path('noticia/deletada', noticiaDeletada, name="noticiaDeletada"),
    path('minhasNoticias', minhasNoticias, name="minhasNoticias"),
    path('minhasNoticias/apagar/<int:noticia_id>', apagarNoticia, name="apagarNoticia"),
    path('minhasNoticias/editar/<int:noticia_id>', editarNoticia, name="editarNoticia"),
]

LPC/Django/noticias/app_noticias/models.py
from django.contrib.auth.models import User
from django.db import models


class Pessoa(models.Model):
    usuario = models.OneToOneField(
        User, on_delete=models.CASCADE, verbose_name='Usuário')
    nome = models.CharField(verbose_name='Nome', max_length=130)
    data_de_nascimento = models.DateField()
    email = models.EmailField(verbose_name='E-mail', null=True, blank=True)

    def __str__(self):
        return self.nome

class Tag(models.Model):
    nome = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64)

    def __str__(self):
        return self.nome


class Noticia(models.Model):
    class Meta:
        verbose_name = 'Notícia'
        verbose_name_plural = 'Notícias'

    autor = models.ForeignKey(Pessoa, on_delete=models.CASCADE, null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    titulo = models.CharField(max_length=120, null=True, blank=True)
    resumo = models.TextField(max_length=500, null=True, blank=True)
    descricao = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.titulo


class MensagemDeContato(models.Model):
    nome = models.CharField(max_length=120)
    email = models.EmailField()
    mensagem = models.TextField()
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email

LPC/Django/noticias/app_noticias/forms.py
from django import forms
from django.contrib.auth.forms import User
from app_noticias.models import Tag

class ContatoForm(forms.Form):
    nome = forms.CharField(max_length=120)
    email = forms.EmailField(required=False)
    mensagem = forms.CharField(widget=forms.Textarea)

class TagForm(forms.Form):
    nome = forms.CharField(max_length=120)
    slug = forms.SlugField()

class AddNoticiaForm(forms.Form):
    autor = User()
    tags = forms.ModelMultipleChoiceField(widget = forms.CheckboxSelectMultiple, queryset = Tag.objects.all())
    titulo = forms.CharField(max_length=120)
    resumo = forms.CharField(max_length=500, widget=forms.Textarea)
    descricao = forms.CharField(widget=forms.Textarea)

LPC/Django/noticias/app_noticias/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic.edit import FormView
from django.http import HttpResponse, Http404, HttpResponseRedirect
from app_noticias.forms import ContatoForm, TagForm, AddNoticiaForm
from django.contrib.auth.models import User
from app_noticias.models import Tag
from django import forms

from app_noticias.models import Noticia, MensagemDeContato, Tag

def home_page(request):
    return render(request, 'app_noticia/home_page.html', {})

def resumo_template(request):
    noticias = []

    for i in Noticia.objects.all():
        noticias.insert(0, i) 

    return render(request, 'app_noticia/resumo.html', {'noticia': noticias})

def detalhes_noticia(request, noticia_id):
    noticia = Noticia.objects.get(pk=noticia_id)
    return render(request, 'app_noticia/detalhe.html', { 'noticia': noticia })

def ContatoView(request):
    formulario = ContatoForm()
    return render(request, 'app_noticia/contato.html', {'form':formulario})

def contato(request):
    formulario = ContatoForm()
    return render(request, 'app_noticia/contato.html', {})

def salvarMensagem(request):
    if request.method == 'POST':
        dados = request.POST

        mensagem = MensagemDeContato()

        mensagem.nome = dados.get('nome')
        mensagem.email = dados.get('email')
        mensagem.mensagem = dados.get('mensagem')

        if '@gmail.com' in mensagem.email:
            return HttpResponse('Provedor de email não suportado.')

        palavras = ['defeito', 'erro', 'problema']
        for i in palavras:
            if i in mensagem.mensagem:
                return HttpResponse('A mensagem contem palavras não permitidas.')
        
        mensagem.save()

        return render(request, 'app_noticia/contato_sucesso.html', {})

def tag(request):
    if request.user.is_authenticated:
        formulario = TagForm()
        return render(request, 'app_noticia/tag.html', {'form': formulario})
    else:
        return render(request, 'app_noticia/erro_acesso.html', {})

def salvarTag(request):
    if request.method == 'POST':
        dados = request.POST

        tag = Tag()

        tag.nome = dados.get('nome')
        tag.slug = dados.get('slug')

        tag.save()

        return render(request, 'app_noticia/tag_sucesso.html', {})


def addNoticia(request):
    tags = Tag.objects.all()

    if request.user.is_authenticated:
        formulario = AddNoticiaForm()
        return render(request, 'app_noticia/noticia_adicionar.html', {'form': formulario, 'tags':tags})
    else:
        return render(request, 'app_noticia/erro_acesso.html', {})

def postarNoticia(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            dados = request.POST

            noticia = Noticia()

            noticia.autor = User.objects.get(username = request.user).pessoa
            noticia.titulo = dados.get('titulo')
            noticia.resumo = dados.get('resumo')
            noticia.descricao = dados.get('descricao')
            noticia.save()

            for i in dados.getlist('tags'):
                noticia.tags.add(Tag.objects.get(pk=i))
            

            return render(request, 'app_noticia/noticia_postada.html', {})
    else:
        return render(request, 'app_noticia/erro_acesso.html', {})

def postarNoticiaEditada(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            dados = request.POST
            noticia = Noticia.objects.get(pk = dados.get('id'))

            noticia.titulo = dados.get('titulo')
            noticia.resumo = dados.get('resumo')
            noticia.descricao = dados.get('descricao')
            noticia.save()
            
            for i in dados.getlist('tags'):
                if not Tag.objects.get(pk = i) in noticia.tags.all():
                    noticia.tags.add(Tag.objects.get(pk = i))

            return render(request, 'app_noticia/noticia_editada.html', {})
    else:
        return render(request, 'app_noticia/erro_acesso.html', {})

def minhasNoticias(request):
    if request.user.is_authenticated:
        user = User.objects.get(username = request.user).pessoa
        noticias = []

        for i in Noticia.objects.filter(autor = user):
            noticias.insert(0, i)  

        return render(request, 'app_noticia/noticia_pessoais.html', {'noticias':noticias})
    else:
        return render(request, 'app_noticia/erro_acesso.html', {})

def apagarNoticia(request, noticia_id):    
    if request.user.is_authenticated:
        noticia = Noticia.objects.get(pk=noticia_id)
        return render(request, 'app_noticia/noticia_confirmar_delete.html', {'noticia':noticia})
    else:
        return render(request, 'app_noticia/erro_acesso.html', {})

def editarNoticia(request, noticia_id):    
    tags = Tag.objects.all()

    if request.user.is_authenticated:
        formulario = AddNoticiaForm()
        noticia = Noticia.objects.get(pk=noticia_id)
        return render(request, 'app_noticia/noticia_editar.html', {'form':formulario, 'noticia':noticia, 'tags':tags})
    else:
        return render(request, 'app_noticia/erro_acesso.html', {})

def deleteNoticia(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            dados = request.POST

            noticia = Noticia.objects.get(pk = dados.get('id'))
            noticia.delete()

            return render(request, 'app_noticia/noticia_apagada.html')
        else:
            return render(request, 'app_noticia/erro_acesso.html', {})

def noticiaDeletada(request):
    if request.user.is_authenticated:
        user = User.objects.get(username = request.user).pessoa
        noticias = []

        for i in Noticia.objects.filter(autor = user):
            noticias.insert(0, i)  

        return render(request, 'app_noticia/noticia_pessoais.html', {'noticias':noticias})
    else:
        return render(request, 'app_noticia/erro_acesso.html', {})

LPC/Django/noticias/app_noticias/templates/app_noticia/contato.html
{% extends "app_noticia/main.html" %}

{% block container %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
    </form>
{% endblock %}

LPC/Django/noticias/app_noticias/templates/app_noticia/contato_sucesso.html
{% extends "app_noticia/main.html" %}

{% block container %}
    <h1>Mensagem enviada com sucesso</h1>
{% endblock %}

LPC/Django/noticias/app_noticias/templates/app_noticia/detalhe.html
{% extends "app_noticia/main.html" %}

{% block container %}
    <h1> {{ noticia.titulo }} </h1>
    <small> {{ noticia.autor }} </small>
    <hr>
    <p style="text-align: justify; max-width: 1000px;"> {{ noticia.descricao }} </p>
{% endblock %}

LPC/Django/noticias/app_noticias/templates/app_noticia/erro_acesso.html
{% extends "app_noticia/main.html" %}

{% block container %}
    
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Você não possui permissão de acesso!</h4>
        <p class="mb-0"><a href="http://localhost:8000/conta/login/">Autentique-se aqui.</a></p>
    </div>
    
{% endblock %}

LPC/Django/noticias/app_noticias/templates/app_noticia/home_page.html
{% extends "app_noticia/main.html" %}

{% block container %}
    <h1 class="site-heading text-center text-black d-none d-lg-block">Bem vindo ao Notição!</h1>
    <p><a href="/resumo"> Resumo das noticias </a></p>
{% endblock %}

LPC/Django/noticias/app_noticias/templates/app_noticia/main.html
<html lang="br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Saitezão</title>


    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <style>

        .navbar {
            justify-content: space-between;
        }

        body {
            padding-top: 5rem;
        }
        .starter-template {
            padding: 3rem 1.5rem;
            text-align: center;
        }

        .tags {
          max-width: 400px;
        }

        .col-md-4 {
          max-width: 350px;
        }

        .col-md-4 .card-img a img {
          filter: opacity(0%);
          transition: opacity 0.2s;
          
          -webkit-transition:filter 0.5s ease-out;
          -moz-transition:filter 0.5s ease-out;
          -o-transition:filter 0.5s ease-out;
          -ms-transition:filter 0.5s ease-out;
        }

        .col-md-4:hover .card-img a img {
          filter: opacity(100%);

          filter:alpha(opacity=100);
          -moz-opacity:1;
          opacity:1;
        }

        a:hover {
          text-decoration: none!important;
        }

        .dropdown:hover .dropdown-menu {
            display: block;
            position: absolute;
            transform: translate3d(5px, 28px, 0px); /* distancia entre menu e btn */
            top: 0px;
            left: 0px;
            will-change: transform;
        }
    </style>

  </head>
  <body >
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <ul class="nav">
        <li>
          <a class="navbar-brand" href="{% url 'resumo' %}">Saitezão</a>
        </li>
        
        <li>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="{% url 'minhasNoticias' %}">Minhas notícias</a>
              <a class="dropdown-item" href="{% url 'adicionarNoticia' %}">Postar notícia</a>
              <a class="dropdown-item" href="{% url 'tag' %}">Adicionar Tag</a>
            </div>
          </div>
        </li>

      </ul>

      <div class="login">
          {% if not user.is_authenticated %}
              <a class="btn btn-primary" href="{% url 'login' %}">Entrar</a>
          {% else %}
              <a class="btn btn-danger" href="{% url 'logout' %}">Sair</a>
          {% endif %}
      </div>
    </nav>

  <main role="main" class="container">

    {% block container %}
    {% endblock %}

  </main>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
  <script src="https://getbootstrap.com/docs/4.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
</html>

LPC/Django/noticias/app_noticias/templates/app_noticia/noticia_adicionar.html
{% extends "app_noticia/main.html" %}

{% block container %}
    
    <form action="noticia/adicionar" method="POST">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        <div class="form form-group col-md-6">
            <div class="tags">
                <label>Tags</label> <br>
                {% for i in tags %}
                    <div class="form-check form-check-inline" id="teste id div" ::marker>
                        <input class="form-check-input" type="checkbox" name="tags" id="idt" value="{{ i.pk }}">
                        <label class="form-check-label" for="nada">{{ i.nome }}</label>
                    </div>
                {% endfor %}
            </div>

            <hr>
            <label for="id_titulo">Titulo</label>
            <input class="form-control" id="id_titulo" name="titulo" type="text" autocomplete="off" placeholder="Título da notícia" required>

            <hr>
            <label for="id_resumo">Resumo</label>
            <textarea class="form-control" name="resumo" id="id_resumo" rows="3" maxlength="500" required></textarea>

            <hr>
            <label for="id_descricao">Descrição</label>
            <textarea class="form-control" name="descricao" id="id_descricao" rows="9" required></textarea>

            <br>
            <button type="submit" class="btn btn-primary">Postar</button>
        </div>
    </form>

    <script>
        a = document.getElementsByClassName('form-check form-check-inline');
        for (var i = 0; i < a.length; i++) {
            a[i].id = 'id_tags_'+i;
            b = document.getElementById('idt')
            b.setAttribute('id', 'id_tags_'+i);
            a[i].children[1].attributes.for.value = 'id_tags_'+i;

        };


    </script>
    
{% endblock %}

LPC/Django/noticias/app_noticias/templates/app_noticia/noticia_apagada.html
{% extends "app_noticia/main.html" %}

{% block container %}

    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Notícia removida com sucesso!</h4>
        <a href="{% url 'minhasNoticias' %}" class="btn btn-info">Voltar para minhas notícias</a>
    </div>

{% endblock %}

LPC/Django/noticias/app_noticias/templates/app_noticia/noticia_confirmar_delete.html
{% extends "app_noticia/main.html" %}

{% block container %}

<form action="/noticia/delete" method="POST" style="max-width: 600px;">
    {% csrf_token %}

    <div class="form-group">
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Apagar notícia!</h4>
            <p>Você está preste a apagar uma notícia do banco de dados. Esta é uma ação permanente. </p>
            <hr>
            <p class="mb-0">Tem certeza que deseja apagar esta notícia?</p>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
            <div class="col" style="color: #007bff;">
                <div class="card mb-4 shadow-sm p-3">
                    <a href="/noticia/{{ noticia.id }}">
                        <h4>{{ noticia.titulo }}</h4>
                    </a>
                    <div class="card-body">
                        <p class="card-text" style="text-align: justify;"> {{ noticia.resumo }} </p>
                        <div class="d-flex justify-content-space-between">
                            <ul class="nav"> <strong>Tags:</strong> 
                                {% for j in noticia.tags.all %}
                                    <li class="nav-item" style="margin-right: 1px; margin-left: 3px; border-bottom: 1px double;">
                                        {{ j }}
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <input type="submit" id="{{ noticia.id }}" class="btn btn-danger" value="Apagar"/>
        <a href="{% url 'minhasNoticias' %}" class="btn btn-secondary"> Cancelar</a>
        <input class="form-control" id="id_id" name="id" type="number" value="{{ noticia.id }}" style="visibility: hidden;">
    </div>
</form>

{% endblock %}

LPC/Django/noticias/app_noticias/templates/app_noticia/noticia_editar.html
{% extends "app_noticia/main.html" %}

{% block container %}
    
    <form action="salvarEdicao" method="POST">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        <div class="form form-group col-md-6">
            <div class="tags">
                <label>Tags</label> <br>
                {% for i in tags %}
                        {% if i in noticia.tags.all %}
                            <div class="form-check form-check-inline" id="teste id div" ::marker>
                                <input class="form-check-input" checked='true' type="checkbox" name="tags" id="idt" value="{{ i.pk }}">
                                <label class="form-check-label" for="nada">{{ i.nome }}</label>
                            </div>
                        {% else %}
                            <div class="form-check form-check-inline" id="teste id div" ::marker>
                                <input class="form-check-input" type="checkbox" name="tags" id="idt" value="{{ i.pk }}">
                                <label class="form-check-label" for="nada">{{ i.nome }}</label>
                            </div>
                        {% endif %}
                {% endfor %}
            </div>

            <hr>
            <label for="id_titulo">Titulo</label>
            <input class="form-control" id="id_titulo" name="titulo" type="text" autocomplete="off">

            <hr>
            <label for="id_resumo">Resumo</label>
            <textarea class="form-control" name="resumo" id="id_resumo" rows="3" maxlength="500"></textarea>

            <hr>
            <label for="id_descricao">Descrição</label>
            <textarea class="form-control" name="descricao"  id="id_descricao" rows="9"></textarea>

            <input type="number" id="id_id" name="id" value="{{ noticia.pk }}" style="visibility: hidden;">

            <br>
            <button type="submit" class="btn btn-primary">Postar</button>
        </div>
    </form>

    <script>
        a = document.getElementsByClassName('form-check form-check-inline');
        for (var i = 0; i < a.length; i++) {
            a[i].id = 'id_tags_'+i;
            b = document.getElementById('idt')
            b.setAttribute('id', 'id_tags_'+i);
            a[i].children[1].attributes.for.value = 'id_tags_'+i;

        };

        document.getElementById('id_titulo').value = `{{ noticia.titulo }}`;
        document.getElementById('id_resumo').innerHTML = `{{ noticia.resumo }}`;
        document.getElementById('id_descricao').innerHTML = `{{ noticia.descricao }}`;

    </script>
    
{% endblock %}

LPC/Django/noticias/app_noticias/templates/app_noticia/noticia_pessoais.html
{% extends "app_noticia/main.html" %}
{% block container %}
<a class="btn btn-info btn-lg btn-block" href="{% url 'adicionarNoticia' %}" type="button">Adicionar notícia</a>
<form action="." method="POST"></form>
    <div class="row">
        {% for i in noticias %}
            <div class="col-md-4" style="color: #007bff;">
                <div class="card mb-4 shadow-sm p-3">
                    <a href="/noticia/{{ i.id }}">
                        <h4>{{ i.titulo }}</h4>
                    </a>
                        <div class="card-body">
                        <p class="card-text" style="text-align: justify;"> {{ i.resumo }} </p>
                            <div class="d-flex justify-content-space-between">
                                <ul class="nav"> <strong>Tags:</strong> 
                                    {% for j in i.tags.all %}
                                        <li class="nav-item" style="margin-right: 1px; margin-left: 3px; border-bottom: 1px double;">
                                            {{ j }}
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>

                            <div class="card-img" >
                                <a href="/minhasNoticias/editar/{{ i.id }}">
                                    <img src="https://www.flaticon.com/svg/static/icons/svg/1263/1263925.svg" title="Editar notícia" id="noticia_{{ i.pk }}" onclick="delNoticia('noticia_{{ i.pk }}')" alt="Apagar notícia" width="30px" style="position: relative; left: 85%; top: 30px;">
                                </a>
                                <a href="/minhasNoticias/apagar/{{ i.id }}">
                                    <img src="https://www.flaticon.com/svg/static/icons/svg/1263/1263922.svg" title="Apagar notícia" id="noticia_{{ i.pk }}" onclick="delNoticia('noticia_{{ i.pk }}')" alt="Apagar notícia" width="30px" style="position: relative; left: 85%; top: 30px;">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            
        {% endfor %}
    </div>
{% endblock %}

LPC/Django/noticias/app_noticias/templates/app_noticia/resumo.html
{% extends "app_noticia/main.html" %}
{% block container %}
<h1>Notícias</h1>
<div class="row">
    {% for i in noticia %}
        <a href="/noticia/{{ i.id }}">
            <div class="col-md-4">
            <div class="card mb-4 shadow-sm p-3">
                <h4>{{ i.titulo }}</h4>
                <div class="card-body">
                <p class="card-text" style="text-align: justify; max-width: 400px;"> {{ i.resumo }} </p>
                <div class="d-flex justify-content-between align-items-center">
                    <ul class="nav"> <strong>Tags:</strong> 
                        {% for j in i.tags.all %}
                            <li class="nav-item" style="margin-right: 1px; margin-left: 3px; border-bottom: 1px double;">
                                {{ j }}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                </div>
            </div>
            </div>
        </a>
    {% endfor %}
</div>
{% endblock %}

LPC/Django/noticias/app_noticias/templates/app_noticia/tag.html
{% extends "app_noticia/main.html" %}

{% block container %}

    <form class="form-signin" action="tags/adicionar" method="POST" 
    style="max-width: 400px; width: 100%; position: fixed; top: 30%; left: 35%;">
        {% csrf_token %}
        <label for="id_nome" class="sr-only">Login</label>
        <input type="text" id="id_tag" name="nome"
         class="form-control" placeholder="Nome da tag" required autofocus>
        <label for="id_slug" class="sr-only">Senha</label>
        <input type="text" name="slug" id="id_slug" class="form-control" placeholder="Slug da tag" required>
        <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Criar</button>
    </form>
    
{% endblock %}

LPC/Django/noticias/app_noticias/templates/app_noticia/tag_sucesso.html
{% extends "app_noticia/main.html" %}

{% block container %}
    
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Tag adicionada!</h4>
        <p class="mb-0"><a href="{% url 'tag' %}">Adicionar outra tag.</a></p>
    </div>
    
{% endblock %}